In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [48]:
df = pd.read_csv("diabetes_prediction_dataset.csv")
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [49]:
# get rid of no info smoking rows
df = df[ (df["smoking_history"] != "No Info") & (df["gender"] != "Other") ]

for col in df.columns:
    print(df.groupby(col).size())

gender
Female    38852
Male      25320
dtype: int64
age
0.16        3
0.24        5
0.32        4
0.40        4
0.48        4
         ...
76.00     523
77.00     536
78.00     486
79.00     426
80.00    3822
Length: 101, dtype: int64
hypertension
0    57889
1     6283
dtype: int64
heart_disease
0    61153
1     3019
dtype: int64
smoking_history
current         9286
ever            4003
former          9352
never          35092
not current     6439
dtype: int64
bmi
10.08    1
10.19    1
10.40    1
10.50    1
10.77    1
        ..
81.73    1
83.74    1
88.72    1
88.76    1
91.82    1
Length: 3943, dtype: int64
HbA1c_level
3.5    4836
4.0    4677
4.5    4729
4.8    4740
5.0    4674
5.7    5376
5.8    5291
6.0    5321
6.1    5164
6.2    5424
6.5    5292
6.6    5438
6.8     528
7.0     513
7.5     534
8.2     541
8.8     546
9.0     548
dtype: int64
blood_glucose_level
80     4434
85     4274
90     4384
100    4431
126    4876
130    4957
140    5025
145    4878
155    4923
158    4460
159    4968
160    4998
200    4873
220     501
240     518
260     526
280     599
300     547
dtype: int64
diabetes
0    57126
1     7046
dtype: int64

In [55]:
pd.DataFrame.to_csv(df, "diabetes_clean.csv")

In [51]:
df.groupby("smoking_history").size()

smoking_history
current         9286
ever            4003
former          9352
never          35092
not current     6439
dtype: int64

In [52]:
df.replace("not current", "former", inplace=True)
df.groupby("smoking_history").size()

/tmp/ipykernel_4328/4020799684.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace("not current", "former", inplace=True)

smoking_history
current     9286
ever        4003
former     15791
never      35092
dtype: int64

In [64]:
df_ever_current = df.replace("ever", "current")
df_ever_former = df.replace("ever", "former")
df_ever_excluded = df[ df["smoking_history"] != "ever" ]

df_smoking = {"current": df_ever_current, "former": df_ever_former, "excluded": df_ever_excluded}

for key, value in df_smoking.items():
    print(str("ever=") + key, value.groupby("smoking_history").size())

ever=current smoking_history
current    13289
former     15791
never      35092
dtype: int64
ever=former smoking_history
current     9286
former     19794
never      35092
dtype: int64
ever=excluded smoking_history
current     9286
former     15791
never      35092
dtype: int64

In [73]:
# treat df smoking ever excluded as the clean dataframe
df = df_ever_excluded
df.to_csv("diabetes_clean.csv", index=False)